/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.danisoka.bulkmailer.app.views.windows.panels;

import hr.danisoka.bulkmailer.app.models.Session;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

/**
 *
 * @author Danijel
 */
public class SessionContainerPanel extends javax.swing.JPanel {

    /**
     * Creates new form SessionContainerPanel
     */
    public SessionContainerPanel(Session session) {
        initComponents();
        this.session = session;        
        populateView();
        setupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblSessionName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcboxDataFile = new javax.swing.JCheckBox();
        jcboxTemplateFile = new javax.swing.JCheckBox();
        jcboxGroup = new javax.swing.JCheckBox();
        lblAttempt = new javax.swing.JLabel();
        lblAttemptValue = new javax.swing.JLabel();
        lblCreatedAt = new javax.swing.JLabel();
        lblCreatedAtValue = new javax.swing.JLabel();
        btnStartSession = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        setMinimumSize(new java.awt.Dimension(686, 160));
        setPreferredSize(new java.awt.Dimension(686, 160));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        layout.rowHeights = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        setLayout(layout);

        lblSessionName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSessionName.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(lblSessionName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSeparator1, gridBagConstraints);

        jcboxDataFile.setText("Datoteka podataka studenata");
        jcboxDataFile.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        add(jcboxDataFile, gridBagConstraints);

        jcboxTemplateFile.setText("Datoteka predloška e-maila");
        jcboxTemplateFile.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        add(jcboxTemplateFile, gridBagConstraints);

        jcboxGroup.setText("Slanje u timovima");
        jcboxGroup.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        add(jcboxGroup, gridBagConstraints);

        lblAttempt.setText("Broj slanja:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(lblAttempt, gridBagConstraints);

        lblAttemptValue.setText("##");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(lblAttemptValue, gridBagConstraints);

        lblCreatedAt.setText("Kreirano:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(lblCreatedAt, gridBagConstraints);

        lblCreatedAtValue.setText("12.11.2020. 14:30");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(lblCreatedAtValue, gridBagConstraints);

        btnStartSession.setText("Šalji skupni e-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 2;
        add(btnStartSession, gridBagConstraints);

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Obriši sesiju");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnDelete, gridBagConstraints);

        btnUpdate.setText("Ažuriraj sesiju");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnUpdate, gridBagConstraints);

        btnReports.setText("Otvori izvješća");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnReports, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStartSession;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcboxDataFile;
    private javax.swing.JCheckBox jcboxGroup;
    private javax.swing.JCheckBox jcboxTemplateFile;
    private javax.swing.JLabel lblAttempt;
    private javax.swing.JLabel lblAttemptValue;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblCreatedAtValue;
    private javax.swing.JLabel lblSessionName;
    // End of variables declaration//GEN-END:variables

    private Session session;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.YYYY. HH:mm");
    
    private void populateView() {
        String sessionName = session.getName() != null ? session.getName() : String.format("Sessija kreirana %s", sdf.format(session.getCreatedAt()));
        lblSessionName.setText(sessionName);
        jcboxDataFile.setSelected(session.getDataFilePath() != null && !session.getDataFilePath().isEmpty());
        jcboxTemplateFile.setSelected(session.getTemplateFilePath()!= null && !session.getTemplateFilePath().isEmpty());
        jcboxGroup.setSelected(session.hasGroup());
        lblAttemptValue.setText(session.getAttempts() != null ? String.valueOf(session.getAttempts().size()) : "-");
        lblCreatedAtValue.setText(sdf.format(session.getCreatedAt()));
    }
    
    private void setupButtons() {
        btnStartSession.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                startBulkMailSession();
            }
        });
        
        btnUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateBulkMailSession();
            }
        });
        
        btnDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteBulkMailSession();
            }
        });
        
        btnReports.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showBulkMailSessionReports();
            }
        });
    }
    
    private void startBulkMailSession() {
        
    }
    
    private void updateBulkMailSession() {
        
    }
    
    private void deleteBulkMailSession() {
        
    }
    
    private void showBulkMailSessionReports() {
        
    }
}
