package hr.danisoka.bulkmailer.app.views.windows.dialogs;

import hr.danisoka.bulkmailer.app.models.Session;
import java.text.SimpleDateFormat;

public class SessionInfoDialog extends javax.swing.JDialog {

    public SessionInfoDialog(java.awt.Frame parent, boolean modal, Session session) {
        super(parent, modal);
        initComponents();
        this.session = session;
        populateView();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblSessionName = new javax.swing.JLabel();
        lblCreatedAt = new javax.swing.JLabel();
        lblCreatedAtValue = new javax.swing.JLabel();
        lblStudentDataFile = new javax.swing.JLabel();
        lblStudentDataFilePath = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblEmailColumn = new javax.swing.JLabel();
        lblEmailColumnValue = new javax.swing.JLabel();
        lblGroupIndicator = new javax.swing.JLabel();
        lblGroupIndicatorValue = new javax.swing.JLabel();
        lblGroupColumn = new javax.swing.JLabel();
        lblGroupColumnValue = new javax.swing.JLabel();
        lblTemplateFile = new javax.swing.JLabel();
        lblTemplateFilePath = new javax.swing.JLabel();
        lblHolderStart = new javax.swing.JLabel();
        lblHolderStartValue = new javax.swing.JLabel();
        lblHolderEnd = new javax.swing.JLabel();
        lblHolderEndValue = new javax.swing.JLabel();
        lblAttempts = new javax.swing.JLabel();
        lblAttemptsCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 300));
        setPreferredSize(new java.awt.Dimension(900, 350));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        lblSessionName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSessionName.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblSessionName, gridBagConstraints);

        lblCreatedAt.setText("Kreirano: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblCreatedAt, gridBagConstraints);

        lblCreatedAtValue.setText("jLabel1");
        lblCreatedAtValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblCreatedAtValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        getContentPane().add(lblCreatedAtValue, gridBagConstraints);

        lblStudentDataFile.setText("Datoteka studenata: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblStudentDataFile, gridBagConstraints);

        lblStudentDataFilePath.setText("jLabel1");
        lblStudentDataFilePath.setMinimumSize(new java.awt.Dimension(500, 14));
        lblStudentDataFilePath.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        getContentPane().add(lblStudentDataFilePath, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        lblEmailColumn.setText("Stupac za e-mail: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblEmailColumn, gridBagConstraints);

        lblEmailColumnValue.setText("jLabel1");
        lblEmailColumnValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblEmailColumnValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        getContentPane().add(lblEmailColumnValue, gridBagConstraints);

        lblGroupIndicator.setText("Timsko slanje: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblGroupIndicator, gridBagConstraints);

        lblGroupIndicatorValue.setText("jLabel1");
        lblGroupIndicatorValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblGroupIndicatorValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        getContentPane().add(lblGroupIndicatorValue, gridBagConstraints);

        lblGroupColumn.setText("Stupac za tim: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblGroupColumn, gridBagConstraints);

        lblGroupColumnValue.setText("jLabel1");
        lblGroupColumnValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblGroupColumnValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        getContentPane().add(lblGroupColumnValue, gridBagConstraints);

        lblTemplateFile.setText("Datoteka predloška e-maila:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblTemplateFile, gridBagConstraints);

        lblTemplateFilePath.setText("jLabel1");
        lblTemplateFilePath.setMinimumSize(new java.awt.Dimension(500, 14));
        lblTemplateFilePath.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        getContentPane().add(lblTemplateFilePath, gridBagConstraints);

        lblHolderStart.setText("Početak placeholdera: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblHolderStart, gridBagConstraints);

        lblHolderStartValue.setText("jLabel1");
        lblHolderStartValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblHolderStartValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        getContentPane().add(lblHolderStartValue, gridBagConstraints);

        lblHolderEnd.setText("Kraj placeholdera: ");
        lblHolderEnd.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblHolderEnd, gridBagConstraints);

        lblHolderEndValue.setText("jLabel1");
        lblHolderEndValue.setMinimumSize(new java.awt.Dimension(500, 14));
        lblHolderEndValue.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        getContentPane().add(lblHolderEndValue, gridBagConstraints);

        lblAttempts.setText("Broj slanja: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(lblAttempts, gridBagConstraints);

        lblAttemptsCount.setText("jLabel1");
        lblAttemptsCount.setMinimumSize(new java.awt.Dimension(500, 14));
        lblAttemptsCount.setPreferredSize(new java.awt.Dimension(500, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 24;
        getContentPane().add(lblAttemptsCount, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblAttemptsCount;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblCreatedAtValue;
    private javax.swing.JLabel lblEmailColumn;
    private javax.swing.JLabel lblEmailColumnValue;
    private javax.swing.JLabel lblGroupColumn;
    private javax.swing.JLabel lblGroupColumnValue;
    private javax.swing.JLabel lblGroupIndicator;
    private javax.swing.JLabel lblGroupIndicatorValue;
    private javax.swing.JLabel lblHolderEnd;
    private javax.swing.JLabel lblHolderEndValue;
    private javax.swing.JLabel lblHolderStart;
    private javax.swing.JLabel lblHolderStartValue;
    private javax.swing.JLabel lblSessionName;
    private javax.swing.JLabel lblStudentDataFile;
    private javax.swing.JLabel lblStudentDataFilePath;
    private javax.swing.JLabel lblTemplateFile;
    private javax.swing.JLabel lblTemplateFilePath;
    // End of variables declaration//GEN-END:variables

    private Session session;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.YYYY. HH:mm");
    
    private void populateView() {
        lblSessionName.setText(session.getName() == null ? "-" : session.getName());
        lblCreatedAtValue.setText(session.getCreatedAt() == null ?  "-" : sdf.format(session.getCreatedAt()));
        lblStudentDataFilePath.setText(session.getDataFilePath() == null ? "-" : session.getDataFilePath());
        lblEmailColumnValue.setText(session.getEmailColumn() == null ? "-" : session.getEmailColumn());
        lblGroupIndicatorValue.setText(session.hasGroup() ? "DA" : "NE");
        lblGroupColumnValue.setText(session.getGroupColumn() == null ? "-" :  session.getGroupColumn());
        lblTemplateFilePath.setText(session.getTemplateFilePath() == null ? "-" : session.getTemplateFilePath());
        lblHolderStartValue.setText(session.getHolderStart() == null ? "-" : session.getHolderStart());
        lblHolderEndValue.setText(session.getHolderEnd() == null ? "-" : session.getHolderEnd());
        lblAttemptsCount.setText(session.getAttempts() == null ? "-" : String.valueOf(session.getAttempts().size()));
    }
}
