/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.danisoka.bulkmailer.app.views.windows;

import hr.danisoka.bulkmailer.app.contracts.NewSessionWinContract;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Danijel
 */
public class NewSessionWindow extends javax.swing.JFrame implements NewSessionWinContract.View{

    /**
     * Creates new form NewSessionWindow
     */
    public NewSessionWindow() {
        initComponents();
        connectHolderTextboxesWithPreview();
        setupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnDataUpload = new javax.swing.JButton();
        lblStudentDataFileName = new javax.swing.JLabel();
        txtStudentDataFileName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblEmailColumn = new javax.swing.JLabel();
        jcbxEmailColumn = new javax.swing.JComboBox<>();
        lblGroupIndicator = new javax.swing.JLabel();
        jtbtnGroupIndicator = new javax.swing.JToggleButton();
        lblGroupColumn = new javax.swing.JLabel();
        jcbxGroupColumn = new javax.swing.JComboBox<>();
        btnTemplateUpload = new javax.swing.JButton();
        lblTemplateFileName = new javax.swing.JLabel();
        txtTemplateFileName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblHolderStart = new javax.swing.JLabel();
        txtHolderStart = new javax.swing.JTextField();
        lblHolderEnd = new javax.swing.JLabel();
        txtHolderEnd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblExampleHolderStart = new javax.swing.JLabel();
        lblExampleHolderName = new javax.swing.JLabel();
        lblExampleHolderEnd = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("Sesija skupnog e-maila");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.POPUP);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        layout.rowHeights = new int[] {0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0};
        getContentPane().setLayout(layout);

        btnDataUpload.setText("Upload podataka studenata");
        btnDataUpload.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(btnDataUpload, gridBagConstraints);

        lblStudentDataFileName.setText("Datoteka studenata:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        getContentPane().add(lblStudentDataFileName, gridBagConstraints);

        txtStudentDataFileName.setMinimumSize(new java.awt.Dimension(300, 20));
        txtStudentDataFileName.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 7;
        getContentPane().add(txtStudentDataFileName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        lblEmailColumn.setText("E-mail pozicija:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblEmailColumn, gridBagConstraints);

        jcbxEmailColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nije odabrano" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jcbxEmailColumn, gridBagConstraints);

        lblGroupIndicator.setText("Timovi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblGroupIndicator, gridBagConstraints);

        jtbtnGroupIndicator.setText("NE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jtbtnGroupIndicator, gridBagConstraints);

        lblGroupColumn.setText("Stupac za tim:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblGroupColumn, gridBagConstraints);

        jcbxGroupColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nije odabrano" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jcbxGroupColumn, gridBagConstraints);

        btnTemplateUpload.setText("Upload predloška e-maila");
        btnTemplateUpload.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        getContentPane().add(btnTemplateUpload, gridBagConstraints);

        lblTemplateFileName.setText("Predložak e-maila:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        getContentPane().add(lblTemplateFileName, gridBagConstraints);

        txtTemplateFileName.setMinimumSize(new java.awt.Dimension(300, 20));
        txtTemplateFileName.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.ipady = 8;
        getContentPane().add(txtTemplateFileName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator2, gridBagConstraints);

        lblHolderStart.setText("Početak placeholdera: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblHolderStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtHolderStart, gridBagConstraints);

        lblHolderEnd.setText("Kraj placeholdera: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(lblHolderEnd, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtHolderEnd, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), java.awt.Color.darkGray));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 4, 0, 4, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        lblExampleHolderStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExampleHolderStart.setText("@@");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lblExampleHolderStart, gridBagConstraints);

        lblExampleHolderName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblExampleHolderName.setText("Poduzece");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lblExampleHolderName, gridBagConstraints);

        lblExampleHolderEnd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExampleHolderEnd.setText("@@");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lblExampleHolderEnd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        btnSave.setText("Kreiraj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(btnSave, gridBagConstraints);

        btnCancel.setText("Odustani");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(btnCancel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDataUpload;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTemplateUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcbxEmailColumn;
    private javax.swing.JComboBox<String> jcbxGroupColumn;
    private javax.swing.JToggleButton jtbtnGroupIndicator;
    private javax.swing.JLabel lblEmailColumn;
    private javax.swing.JLabel lblExampleHolderEnd;
    private javax.swing.JLabel lblExampleHolderName;
    private javax.swing.JLabel lblExampleHolderStart;
    private javax.swing.JLabel lblGroupColumn;
    private javax.swing.JLabel lblGroupIndicator;
    private javax.swing.JLabel lblHolderEnd;
    private javax.swing.JLabel lblHolderStart;
    private javax.swing.JLabel lblStudentDataFileName;
    private javax.swing.JLabel lblTemplateFileName;
    private javax.swing.JTextField txtHolderEnd;
    private javax.swing.JTextField txtHolderStart;
    private javax.swing.JTextField txtStudentDataFileName;
    private javax.swing.JTextField txtTemplateFileName;
    // End of variables declaration//GEN-END:variables

    private File csvFile;
    private NewSessionWinContract.Controller controller;
    private List<String> studentsDataHeaders;
    
    public void setController(NewSessionWinContract.Controller controller) {
        this.controller = controller;
    }
    
    private void connectHolderTextboxesWithPreview() {
        lblExampleHolderStart.setText(txtHolderStart.getText());
        lblExampleHolderEnd.setText(txtHolderEnd.getText());
        
        txtHolderStart.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String value = txtHolderStart.getText();
                lblExampleHolderStart.setText(value);
            }            
        });
        
        txtHolderEnd.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String value = txtHolderEnd.getText();
                lblExampleHolderEnd.setText(value);
            }
        });
    }
    
    private void handleToggleButton(boolean value) {
        jtbtnGroupIndicator.setSelected(value);
        jtbtnGroupIndicator.setText(value ? "DA" :  "NE");
    }
    
    private void setupButtons() {
        jtbtnGroupIndicator.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean value = jtbtnGroupIndicator.isSelected();
                handleToggleButton(value);
            }
        });
        
        btnDataUpload.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleCsvDataUpload();
            }
        });
        
        btnTemplateUpload.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleTemplateUpload();
            }
        });
        
        btnCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleCancelDialog();
            }
        });
        
        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleSaveDialog();
            }
        });
    }
    
    private void handleCsvDataUpload() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV filter", "csv");
        chooser.setFileFilter(filter);
        chooser.setLocale(Locale.forLanguageTag("HR"));
        int outcome = chooser.showDialog(this, null);
        if(outcome == JFileChooser.APPROVE_OPTION) {
            csvFile = chooser.getSelectedFile();
            
            int indexOfdot = csvFile.getName().lastIndexOf(".");
            String onlyName = csvFile.getName().substring(0, indexOfdot);
            txtStudentDataFileName.setText(onlyName);
            
            studentsDataHeaders = controller.fetchHeadersFromStudentsData(csvFile);
            handleCombobox(jcbxEmailColumn, studentsDataHeaders, "Nije odabrano");
            handleCombobox(jcbxGroupColumn, studentsDataHeaders, "Nije odabrano");
            
            controller.analyzeStudentData(csvFile);
        }
    }
    
    private void handleTemplateUpload() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("HTML filter", "html", "xhtml", "htm");
        chooser.setFileFilter(filter);
        chooser.setLocale(Locale.forLanguageTag("HR"));
        int outcome = chooser.showDialog(this, null);
        if(outcome == JFileChooser.APPROVE_OPTION) {
            csvFile = chooser.getSelectedFile();
            int indexOfdot = csvFile.getName().lastIndexOf(".");
            String onlyName = csvFile.getName().substring(0, indexOfdot);
            txtTemplateFileName.setText(onlyName);
        }
    } 
    
    private void handleCancelDialog() {
        this.setVisible(false);
    }
    
    private void handleSaveDialog() {
        
    }
    
    private void handleCombobox(JComboBox cbx, List<String> items, String initialItem) {
        cbx.removeAllItems();
        if(initialItem != null) {
            cbx.addItem(initialItem);
        }
        for(String item : items) {
            cbx.addItem(item);
        }
    }

    @Override
    public void updateEmailColumnCombobox(String selectedValue) {
        jcbxEmailColumn.setSelectedItem(selectedValue);
    }

    @Override
    public void updateGroupColumnCombobox(String selectedValue) {
        jcbxGroupColumn.setSelectedItem(selectedValue);
    }

    @Override
    public void updateGroupIndicator(boolean value) {
        handleToggleButton(value);
        if(!value) {
            jcbxGroupColumn.setSelectedIndex(0);
        }
    }
}
